/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package StoreManagement.GUI;

import StoreManagement.BUS.KhachHangBUS;
import StoreManagement.DTO.KhachHang;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thanh
 */
public class ListKH extends javax.swing.JDialog {

    private KhachHangBUS khBUS = new KhachHangBUS();
    public static KhachHang khachHangSelected = null;
        
    DefaultTableModel dtmListKH;
     public ListKH() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setModal(true);
        Image icon = Toolkit.getDefaultToolkit().getImage("image/logo-icon.png");
        this.setIconImage(icon);
        dtmListKH = (DefaultTableModel) tblListKH.getModel();
        loadtblKH();
    }
    public void loadtblKH(){
        dtmListKH.setRowCount(0);
        
        ArrayList<KhachHang> dskh = null;
        dskh = khBUS.getListKhachHang();
        for (KhachHang kh : dskh) {
            Vector vec = new Vector();
            vec.add(kh.getMaKH());
            vec.add(kh.getHoTen());
            vec.add(kh.getSoDT());
            vec.add(kh.getTongChiTieu());
            vec.add(kh.getTichDiem());
            dtmListKH.addRow(vec);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListKH = new MyCustom.MyTable();
        label1 = new java.awt.Label();
        txtNameKH = new javax.swing.JTextField();
        btnSelectKH = new javax.swing.JButton();
        btnAddKH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblListKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Tên KH", "SDT", "Tổng chi tiêu", "Tích điểm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListKHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListKH);

        label1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        label1.setName(""); // NOI18N
        label1.setText("Tìm khách hàng");

        txtNameKH.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        btnSelectKH.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnSelectKH.setText("Chọn");
        btnSelectKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectKHActionPerformed(evt);
            }
        });

        btnAddKH.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnAddKH.setText("Thêm KH");
        btnAddKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelectKH, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnAddKH, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNameKH, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddKH)
                    .addComponent(btnSelectKH))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblListKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListKHMouseClicked
        // TODO add your handling code here:
        int row = tblListKH.getSelectedRow();
         if (row > -1) {
            String ma = tblListKH.getValueAt(row, 0).toString();
            String ten = tblListKH.getValueAt(row, 1).toString();
            String SDT = tblListKH.getValueAt(row, 2).toString();

            float tongChiTieu = Float.parseFloat(tblListKH.getValueAt(row, 3).toString());
            float tichDiem = Float.parseFloat(tblListKH.getValueAt(row, 4).toString());
            khachHangSelected = new KhachHang(ma, ten, null ,SDT, tongChiTieu, tichDiem);
        }
    }//GEN-LAST:event_tblListKHMouseClicked

    private void btnSelectKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectKHActionPerformed
        // TODO add your handling code here:
        if(khachHangSelected==null){
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn khách hàng nào!","Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }         
        this.dispose();

    }//GEN-LAST:event_btnSelectKHActionPerformed

    private void btnAddKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddKHActionPerformed
        // TODO add your handling code here:
        DlgAddKH addKH = new DlgAddKH();
        addKH.setVisible(true);
        loadtblKH();
    }//GEN-LAST:event_btnAddKHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddKH;
    private javax.swing.JButton btnSelectKH;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private MyCustom.MyTable tblListKH;
    private javax.swing.JTextField txtNameKH;
    // End of variables declaration//GEN-END:variables
}
