/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package StoreManagement.GUI;

import StoreManagement.BUS.CTHDBUS;
import StoreManagement.BUS.HoaDonBUS;
import StoreManagement.DAO.HoaDonDAO;
import StoreManagement.DTO.SanPham;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thanh
 */
public class PnThongKe extends javax.swing.JPanel {

    CTHDBUS cthdBUS = new CTHDBUS();
    HoaDonBUS hdBUS = new HoaDonBUS();
    HoaDonDAO hdDAO = new HoaDonDAO();
   
    DefaultTableModel dtmThongKeSP;
    DefaultTableModel dtmDoanhSoNV;
    public PnThongKe() {
        initComponents();
        dtmThongKeSP = (DefaultTableModel) tblTopSP.getModel();
        dtmDoanhSoNV = (DefaultTableModel) tblDoanhSoNV.getModel();
        
       loadTblThongKeDs();
        
        loadTblThongKeSp();
        loadtblDoanhSoNV();

    }
    private void loadTblThongKeDs(){
        int year = Integer.parseInt(cmbYearTotal.getSelectedItem().toString());
        
        lblQuarter1.setText(hdBUS.getTotalByQuarter(year, 1).toString());
        lblQuarter2.setText(hdBUS.getTotalByQuarter(year, 2).toString());
        lblQuarter3.setText(hdBUS.getTotalByQuarter(year, 3).toString());
        lblQuarter4.setText(hdBUS.getTotalByQuarter(year, 4).toString());
    }
    private void loadTblThongKeSp(){
        dtmThongKeSP.setRowCount(0);
        int month = Integer.parseInt(cmbMonthTopSP.getSelectedItem().toString());
        int year = Integer.parseInt(cmbYearTopSP.getSelectedItem().toString());

        ArrayList<SanPham> lstTopSp = cthdBUS.getTopSP(month, year);
        int count = 1;
         for (SanPham sp : lstTopSp){
            Vector vec = new Vector();
            vec.add(count);
            vec.add(sp.getMaSP());
            vec.add(sp.getTenSP());
            vec.add(sp.getSoLuong());
            count++;
            dtmThongKeSP.addRow(vec);
         }
    }
    private void loadtblDoanhSoNV(){
        dtmDoanhSoNV.setRowCount(0);
        int month = Integer.parseInt(cmbMonthNV.getSelectedItem().toString());
        int year = Integer.parseInt(cmbYearNv.getSelectedItem().toString());
        ArrayList<Vector> lstDoanhSoNV = hdDAO.getDoanhSoNhanVien(month, year);
        
        for (Vector row : lstDoanhSoNV){
            dtmDoanhSoNV.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        lblQuarter1 = new javax.swing.JLabel();
        lblQuarter2 = new javax.swing.JLabel();
        lblQuarter3 = new javax.swing.JLabel();
        lblQuarter4 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblTopSP = new MyCustom.MyTable();
        jLabel58 = new javax.swing.JLabel();
        cmbMonthTopSP = new javax.swing.JComboBox<>();
        jLabel59 = new javax.swing.JLabel();
        cmbYearTopSP = new javax.swing.JComboBox<>();
        cmbYearTotal = new javax.swing.JComboBox<>();
        jLabel60 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblDoanhSoNV = new MyCustom.MyTable();
        jLabel1 = new javax.swing.JLabel();
        cmbMonthNV = new javax.swing.JComboBox<>();
        jLabel62 = new javax.swing.JLabel();
        cmbYearNv = new javax.swing.JComboBox<>();

        setAlignmentX(0);
        setAlignmentY(0);
        setPreferredSize(new java.awt.Dimension(1030, 844));

        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1030, 844));

        jPanel15.setPreferredSize(new java.awt.Dimension(1030, 844));

        jPanel14.setLayout(new java.awt.GridLayout(2, 5));

        jLabel49.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel49.setText("Quý");
        jLabel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(jLabel49);

        jLabel50.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel50.setText("Quý 1");
        jLabel50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(jLabel50);

        jLabel51.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel51.setText("Quý 2");
        jLabel51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(jLabel51);

        jLabel52.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel52.setText("Quý 3");
        jLabel52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(jLabel52);

        jLabel53.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel53.setText("Quý 4");
        jLabel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(jLabel53);

        jLabel54.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel54.setText("Doanh thu");
        jLabel54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(jLabel54);

        lblQuarter1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblQuarter1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(lblQuarter1);

        lblQuarter2.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblQuarter2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(lblQuarter2);

        lblQuarter3.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblQuarter3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(lblQuarter3);

        lblQuarter4.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblQuarter4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(lblQuarter4);

        jLabel55.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel55.setText("SẢN PHẨM BÁN CHẠY ");

        jLabel56.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel56.setText("DOANH THU ");

        tblTopSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Top", "Mã sản phẩm", "Tên sản phẩm", "Số lượng đã bán"
            }
        ));
        jScrollPane7.setViewportView(tblTopSP);

        jLabel58.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel58.setText("Tháng");

        cmbMonthTopSP.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cmbMonthTopSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmbMonthTopSP.setSelectedIndex(5);
        cmbMonthTopSP.setToolTipText("");
        cmbMonthTopSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMonthTopSPActionPerformed(evt);
            }
        });

        jLabel59.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel59.setText("Năm");

        cmbYearTopSP.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cmbYearTopSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022" }));
        cmbYearTopSP.setSelectedIndex(2);
        cmbYearTopSP.setToolTipText("");
        cmbYearTopSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbYearTopSPActionPerformed(evt);
            }
        });

        cmbYearTotal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cmbYearTotal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022" }));
        cmbYearTotal.setSelectedIndex(2);
        cmbYearTotal.setToolTipText("");
        cmbYearTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbYearTotalActionPerformed(evt);
            }
        });

        jLabel60.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel60.setText("Năm");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel55)
                .addGap(352, 352, 352))
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel58)
                        .addGap(18, 18, 18)
                        .addComponent(cmbMonthTopSP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel59)
                        .addGap(18, 18, 18)
                        .addComponent(cmbYearTopSP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jLabel56))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jLabel60)
                        .addGap(18, 18, 18)
                        .addComponent(cmbYearTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(cmbMonthTopSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59)
                    .addComponent(cmbYearTopSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(cmbYearTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        jTabbedPane1.addTab("Tổng quát", jPanel15);

        jLabel57.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel57.setText("DOANH SỐ BÀN HÀNG NHÂN VIÊN");

        tblDoanhSoNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Tên NV", "Doanh số", "Số lượng đơn hàng"
            }
        ));
        jScrollPane8.setViewportView(tblDoanhSoNV);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Tháng");

        cmbMonthNV.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cmbMonthNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmbMonthNV.setSelectedIndex(5);
        cmbMonthNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMonthNVActionPerformed(evt);
            }
        });

        jLabel62.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel62.setText("Năm");

        cmbYearNv.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cmbYearNv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022" }));
        cmbYearNv.setSelectedIndex(2);
        cmbYearNv.setToolTipText("");
        cmbYearNv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbYearNvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel57))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel62))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbYearNv, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMonthNV, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 149, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel57)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbMonthNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(cmbYearNv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thống kê nhân viên", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMonthTopSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMonthTopSPActionPerformed
        // TODO add your handling code here:
        loadTblThongKeSp();

    }//GEN-LAST:event_cmbMonthTopSPActionPerformed

    private void cmbMonthNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMonthNVActionPerformed
        // TODO add your handling code here:
        loadtblDoanhSoNV();
    }//GEN-LAST:event_cmbMonthNVActionPerformed

    private void cmbYearTopSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbYearTopSPActionPerformed
        // TODO add your handling code here:
        loadTblThongKeSp();
    }//GEN-LAST:event_cmbYearTopSPActionPerformed

    private void cmbYearTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbYearTotalActionPerformed
        // TODO add your handling code here:
        loadTblThongKeDs();
    }//GEN-LAST:event_cmbYearTotalActionPerformed

    private void cmbYearNvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbYearNvActionPerformed
        // TODO add your handling code here:
        loadtblDoanhSoNV();

    }//GEN-LAST:event_cmbYearNvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbMonthNV;
    private javax.swing.JComboBox<String> cmbMonthTopSP;
    private javax.swing.JComboBox<String> cmbYearNv;
    private javax.swing.JComboBox<String> cmbYearTopSP;
    private javax.swing.JComboBox<String> cmbYearTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblQuarter1;
    private javax.swing.JLabel lblQuarter2;
    private javax.swing.JLabel lblQuarter3;
    private javax.swing.JLabel lblQuarter4;
    private MyCustom.MyTable tblDoanhSoNV;
    private MyCustom.MyTable tblTopSP;
    // End of variables declaration//GEN-END:variables
}
