/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package StoreManagement.GUI;

import StoreManagement.BUS.CTHDBUS;
import StoreManagement.BUS.HoaDonBUS;
import StoreManagement.DAO.HoaDonDAO;
import StoreManagement.DTO.SanPham;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thanh
 */
public class PnThongKe extends javax.swing.JPanel {

    CTHDBUS cthdBUS = new CTHDBUS();
    HoaDonBUS hdBUS = new HoaDonBUS();
    HoaDonDAO hdDAO = new HoaDonDAO();
    int year = 2022;
   
    DefaultTableModel dtmThongKeSP;
    DefaultTableModel dtmDoanhSoNV;
    public PnThongKe() {
        initComponents();
        dtmThongKeSP = (DefaultTableModel) tblTopSP.getModel();
        dtmDoanhSoNV = (DefaultTableModel) tblDoanhSoNV.getModel();
        
         
        
        lblQuarter1.setText(hdBUS.getTotalByQuarter(year, 1).toString());
        lblQuarter2.setText(hdBUS.getTotalByQuarter(year, 2).toString());
        lblQuarter3.setText(hdBUS.getTotalByQuarter(year, 3).toString());
        lblQuarter4.setText(hdBUS.getTotalByQuarter(year, 4).toString());
        
        loadTblThongKeSp();
        loadtblDoanhSoNV();

    }
    private void loadTblThongKeSp(){
        ArrayList<SanPham> lstTopSp = cthdBUS.getTopSP();
        int count = 1;
         for (SanPham sp : lstTopSp){
            Vector vec = new Vector();
            vec.add(count);
            vec.add(sp.getMaSP());
            vec.add(sp.getTenSP());
            vec.add(sp.getSoLuong());
            count++;
            dtmThongKeSP.addRow(vec);
         }
    }
    private void loadtblDoanhSoNV(){
        ArrayList<Vector> lstDoanhSoNV = hdDAO.getDoanhSoNhanVien();
        
        for (Vector row : lstDoanhSoNV){;
            dtmDoanhSoNV.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        lblQuarter1 = new javax.swing.JLabel();
        lblQuarter2 = new javax.swing.JLabel();
        lblQuarter3 = new javax.swing.JLabel();
        lblQuarter4 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblTopSP = new MyCustom.MyTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblDoanhSoNV = new MyCustom.MyTable();

        setAlignmentX(0);
        setAlignmentY(0);

        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jPanel14.setLayout(new java.awt.GridLayout(2, 5));

        jLabel49.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel49.setText("Quý");
        jLabel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(jLabel49);

        jLabel50.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel50.setText("Quý 1");
        jLabel50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(jLabel50);

        jLabel51.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel51.setText("Quý 2");
        jLabel51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(jLabel51);

        jLabel52.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel52.setText("Quý 3");
        jLabel52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(jLabel52);

        jLabel53.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel53.setText("Quý 4");
        jLabel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(jLabel53);

        jLabel54.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel54.setText("Doanh thu");
        jLabel54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(jLabel54);

        lblQuarter1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblQuarter1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(lblQuarter1);

        lblQuarter2.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblQuarter2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(lblQuarter2);

        lblQuarter3.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblQuarter3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(lblQuarter3);

        lblQuarter4.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblQuarter4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(lblQuarter4);

        jLabel55.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel55.setText("SẢN PHẨM BÁN CHẠY ");

        jLabel56.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel56.setText("DOANH THU NĂM 2022");

        tblTopSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Top", "Mã sản phẩm", "Tên sản phẩm", "Số lượng đã bán"
            }
        ));
        jScrollPane7.setViewportView(tblTopSP);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 371, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel55)
                        .addGap(352, 352, 352))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel56)
                        .addGap(334, 334, 334))))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        jTabbedPane1.addTab("Tổng quát", jPanel15);

        jLabel57.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel57.setText("DOANH SỐ BÀN HÀNG NHÂN VIÊN");

        tblDoanhSoNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Tên NV", "Doanh số", "Số lượng đơn hàng"
            }
        ));
        jScrollPane8.setViewportView(tblDoanhSoNV);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel57)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel57)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thống kê nhân viên", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblQuarter1;
    private javax.swing.JLabel lblQuarter2;
    private javax.swing.JLabel lblQuarter3;
    private javax.swing.JLabel lblQuarter4;
    private javax.swing.JLabel lblQuy1;
    private javax.swing.JLabel lblQuy10;
    private javax.swing.JLabel lblQuy11;
    private javax.swing.JLabel lblQuy12;
    private javax.swing.JLabel lblQuy13;
    private javax.swing.JLabel lblQuy14;
    private javax.swing.JLabel lblQuy15;
    private javax.swing.JLabel lblQuy16;
    private javax.swing.JLabel lblQuy17;
    private javax.swing.JLabel lblQuy18;
    private javax.swing.JLabel lblQuy19;
    private javax.swing.JLabel lblQuy2;
    private javax.swing.JLabel lblQuy20;
    private javax.swing.JLabel lblQuy21;
    private javax.swing.JLabel lblQuy22;
    private javax.swing.JLabel lblQuy23;
    private javax.swing.JLabel lblQuy24;
    private javax.swing.JLabel lblQuy3;
    private javax.swing.JLabel lblQuy4;
    private javax.swing.JLabel lblQuy5;
    private javax.swing.JLabel lblQuy6;
    private javax.swing.JLabel lblQuy7;
    private javax.swing.JLabel lblQuy8;
    private javax.swing.JLabel lblQuy9;
    private MyCustom.MyTable myTable1;
    private MyCustom.MyTable myTable2;
    private MyCustom.MyTable myTable3;
    private MyCustom.MyTable myTable4;
    private MyCustom.MyTable myTable5;
    private MyCustom.MyTable myTable6;
    private MyCustom.MyTable tblDoanhSoNV;
    private MyCustom.MyTable tblTopSP;
    // End of variables declaration//GEN-END:variables
}
