/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package StoreManagement.GUI;

import StoreManagement.BUS.CTHDBUS;
import StoreManagement.BUS.HoaDonBUS;
import StoreManagement.DTO.SanPham;
import java.util.ArrayList;

/**
 *
 * @author thanh
 */
public class PnThongKe extends javax.swing.JPanel {

    CTHDBUS cthdBUS = new CTHDBUS();
    HoaDonBUS hdBUS = new HoaDonBUS();
    int year = 2022;
    ArrayList<SanPham> lstTopSp = cthdBUS.getTopSP();
    
    public PnThongKe() {
        initComponents();
        lblSp1.setText(lstTopSp.get(0).getTenSP());
        lblSp2.setText(lstTopSp.get(1).getTenSP());
        lblSp3.setText(lstTopSp.get(2).getTenSP());
        lblSp4.setText(lstTopSp.get(3).getTenSP());
        lblSp5.setText(lstTopSp.get(4).getTenSP());
        
        lblPrice1.setText(String.valueOf(lstTopSp.get(0).getSoLuong()));
        lblPrice2.setText(String.valueOf(lstTopSp.get(1).getSoLuong()));
        lblPrice3.setText(String.valueOf(lstTopSp.get(2).getSoLuong()));
        lblPrice4.setText(String.valueOf(lstTopSp.get(3).getSoLuong()));
        lblPrice5.setText(String.valueOf(lstTopSp.get(4).getSoLuong()));
        
        lblQuy1.setText(hdBUS.getTotalByQuarter(year, 1).toString());
        lblQuy2.setText(hdBUS.getTotalByQuarter(year, 2).toString());
        lblQuy3.setText(hdBUS.getTotalByQuarter(year, 3).toString());
        lblQuy4.setText(hdBUS.getTotalByQuarter(year, 4).toString());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblQuy1 = new javax.swing.JLabel();
        lblQuy2 = new javax.swing.JLabel();
        lblQuy3 = new javax.swing.JLabel();
        lblQuy4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblSp1 = new javax.swing.JLabel();
        lblPrice1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblSp2 = new javax.swing.JLabel();
        lblPrice2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblSp3 = new javax.swing.JLabel();
        lblPrice3 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblSp4 = new javax.swing.JLabel();
        lblPrice4 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lblSp5 = new javax.swing.JLabel();
        lblPrice5 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setAlignmentX(0);
        setAlignmentY(0);

        jPanel1.setLayout(new java.awt.GridLayout(2, 5));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setText("Quý");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel2.setText("Quý 1");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel3.setText("Quý 2");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel4.setText("Quý 3");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel5.setText("Quý 4");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel6.setText("Doanh thu");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel6);

        lblQuy1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblQuy1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblQuy1);

        lblQuy2.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblQuy2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblQuy2);

        lblQuy3.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblQuy3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblQuy3);

        lblQuy4.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblQuy4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblQuy4);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel16.setText("SẢN PHẨM BÁN CHẠY ");

        jPanel2.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel17.setText("Top");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel17);
        jLabel17.setBounds(0, 0, 80, 56);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel18.setText("Tên sản phẩm");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel18);
        jLabel18.setBounds(78, 0, 480, 56);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel19.setText("Ðã bán");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel19);
        jLabel19.setBounds(557, 0, 100, 56);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel20.setText("1");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel20);
        jLabel20.setBounds(0, 56, 80, 56);

        lblSp1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblSp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblSp1);
        lblSp1.setBounds(78, 56, 480, 56);

        lblPrice1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblPrice1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblPrice1);
        lblPrice1.setBounds(557, 56, 100, 56);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel23.setText("2");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel23);
        jLabel23.setBounds(0, 112, 80, 56);

        lblSp2.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblSp2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblSp2);
        lblSp2.setBounds(78, 112, 480, 56);

        lblPrice2.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblPrice2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblPrice2);
        lblPrice2.setBounds(557, 112, 100, 56);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel26.setText("3");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel26);
        jLabel26.setBounds(0, 168, 80, 56);

        lblSp3.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblSp3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblSp3);
        lblSp3.setBounds(78, 168, 480, 56);

        lblPrice3.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblPrice3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblPrice3);
        lblPrice3.setBounds(557, 168, 100, 56);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel29.setText("4");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel29);
        jLabel29.setBounds(0, 224, 80, 56);

        lblSp4.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblSp4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblSp4);
        lblSp4.setBounds(78, 224, 480, 56);

        lblPrice4.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblPrice4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblPrice4);
        lblPrice4.setBounds(557, 224, 100, 56);

        jLabel33.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel33.setText("5");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel33);
        jLabel33.setBounds(0, 280, 80, 56);

        lblSp5.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblSp5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblSp5);
        lblSp5.setBounds(78, 280, 480, 56);

        lblPrice5.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblPrice5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblPrice5);
        lblPrice5.setBounds(557, 280, 100, 56);

        jLabel32.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel32.setText("DOANH THU NĂM 2022");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel16)))
                .addGap(0, 195, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPrice1;
    private javax.swing.JLabel lblPrice2;
    private javax.swing.JLabel lblPrice3;
    private javax.swing.JLabel lblPrice4;
    private javax.swing.JLabel lblPrice5;
    private javax.swing.JLabel lblQuy1;
    private javax.swing.JLabel lblQuy2;
    private javax.swing.JLabel lblQuy3;
    private javax.swing.JLabel lblQuy4;
    private javax.swing.JLabel lblSp1;
    private javax.swing.JLabel lblSp2;
    private javax.swing.JLabel lblSp3;
    private javax.swing.JLabel lblSp4;
    private javax.swing.JLabel lblSp5;
    // End of variables declaration//GEN-END:variables
}
